### ISSUE TITLE
Cannot compile example httpserver.ino

### ISSUE THREAD

**Issue by Sterpa** [harlequin-tech/WiFlyHQ#56] opened 2016-04-24 20:57 UTC
I can not compile the example file httpserver.ino
Gives an error message:
...WiFlyHQ-master/WiFlyHQ.h:78:28: error: section attribute not allowed for 'prog_char'
 typedef const char PROGMEM prog_char;

What could be the problem?
the author is silent... @chrwei please help!

**Comment by duhovny** [comment] 2016-04-25 18:11
Hey @Sterpa, I had same problem with the last version of Arduino IDE. Rolling back to v1.0 helped to solve this issue.

Also @chrwei has mentioned he fixed this for last version of Arduino IDE in his forked repository. I haven't tried though.

**Comment by chrwei** [comment] 2016-04-25 18:22
that line does not cause problems for me in 1.6.5.  I'm not sure what the issue is in this case.

**Comment by Sterpa** [comment] 2016-04-25 19:41
Very strange... i use 1.6.8 and @chrwei fofk, and cannot solve this... only remark this lines with #define PROGMEM 

```
//#undef PROGMEM 
//#define PROGMEM __attribute__(( section(".progmem.data") )) 
#undef PSTR 
#define PSTR(s) (__extension__({static prog_char __c[] PROGMEM = (s); &__c[0];})) 
```

but i am not shure, that it is right way. Of course rolling back to v1.0 is a wrong way, we go forward, not downshift))

**Comment by chrwei** [comment] 2016-04-25 20:58
so... I followed the posted error instead of actually open the example, and removing those lines should fix it, or maybe wrap them in an ifdef so older versions still use it?

see pull request #57

**Comment by harlequin-tech** [comment] 2016-08-22 20:11
Update merged, thanks.  This code was an old work-around to avoid compiler warnings when using PROGMEM.  Newer Arduino releases have fixed the problem.

**Closed by harlequin-tech** 2016-08-22 20:11 UTC
